#pragma once

#include "field/field.metal.h"

/*
This file was automatically generated by icicle/icicle/backend/metal/scripts/gen_metal_shaders.py
To change the shader, change the template in icicle/icicle/backend/metal/scripts/templates
*/

struct bls12_381ScalarConfig {
  static constant constexpr uint NLIMBS = 8;
  static constant constexpr unsigned modulus_bit_count = 255;
  static constant constexpr unsigned num_of_reductions = 1;
  static constant constexpr storage<NLIMBS> modulus = {0x1,       0xffffffff, 0xfffe5bfe, 0x53bda402,
                                                       0x9a1d805, 0x3339d808, 0x299d7d48, 0x73eda753};
  static constant constexpr storage<NLIMBS> modulus_2 = {0x2,        0xfffffffe, 0xfffcb7fd, 0xa77b4805,
                                                         0x1343b00a, 0x6673b010, 0x533afa90, 0xe7db4ea6};
  static constant constexpr storage<NLIMBS> modulus_4 = {0x4,        0xfffffffc, 0xfff96ffb, 0x4ef6900b,
                                                         0x26876015, 0xcce76020, 0xa675f520, 0xcfb69d4c};
  static constant constexpr storage<NLIMBS> neg_modulus = {0xffffffff, 0x0,        0x1a401,    0xac425bfd,
                                                           0xf65e27fa, 0xccc627f7, 0xd66282b7, 0x8c1258ac};
  static constant constexpr storage<NLIMBS> rou = {0xb912f1f,  0x1b788f50, 0x70b3e094, 0xc4024ff2,
                                                   0xd168d6c0, 0xfd56dc8,  0x5b416b6f, 0x212d79e};
  static constant constexpr storage<NLIMBS> m = {0x830358e4, 0x509cde80, 0x2f92eb5c, 0xd9410fad,
                                                 0xc1f823b4, 0xe2d772d,  0x7fb78ddf, 0x8d54253b};
  static constant constexpr storage<2 * NLIMBS> modulus_squared = {
    0x1,        0xfffffffe, 0xfffcb7fe, 0xa77e9007, 0x1cdbb005, 0x698ae002, 0x5433f7b8, 0x48aa415e,
    0x4aa9c661, 0xc2611f6f, 0x59934a1d, 0xe9593f9,  0xef2cc20f, 0x520c13db, 0xf4bc2778, 0x347f60f3};
  static constant constexpr storage<NLIMBS> montgomery_r = {0xfffffffe, 0x1,        0x34802,    0x5884b7fa,
                                                            0xecbc4ff5, 0x998c4fef, 0xacc5056f, 0x1824b159};
  static constant constexpr storage<NLIMBS> montgomery_r_inv = {0xfe75c040, 0x13f75b69, 0x9dc705f,  0xab6fca8f,
                                                                0x4f77266a, 0x7204078a, 0x30009d57, 0x1bbe8693};
};

struct bls12_381BaseFieldConfig {
  static constant constexpr uint NLIMBS = 12;
  static constant constexpr unsigned modulus_bit_count = 381;
  static constant constexpr unsigned num_of_reductions = 1;
  static constant constexpr storage<NLIMBS> modulus = {0xffffaaab, 0xb9feffff, 0xb153ffff, 0x1eabfffe,
                                                       0xf6b0f624, 0x6730d2a0, 0xf38512bf, 0x64774b84,
                                                       0x434bacd7, 0x4b1ba7b6, 0x397fe69a, 0x1a0111ea};
  static constant constexpr storage<NLIMBS> modulus_2 = {0xffff5556, 0x73fdffff, 0x62a7ffff, 0x3d57fffd,
                                                         0xed61ec48, 0xce61a541, 0xe70a257e, 0xc8ee9709,
                                                         0x869759ae, 0x96374f6c, 0x72ffcd34, 0x340223d4};
  static constant constexpr storage<NLIMBS> modulus_4 = {0xfffeaaac, 0xe7fbffff, 0xc54ffffe, 0x7aaffffa,
                                                         0xdac3d890, 0x9cc34a83, 0xce144afd, 0x91dd2e13,
                                                         0xd2eb35d,  0x2c6e9ed9, 0xe5ff9a69, 0x680447a8};
  static constant constexpr storage<NLIMBS> neg_modulus = {0x5555,     0x46010000, 0x4eac0000, 0xe1540001,
                                                           0x94f09db,  0x98cf2d5f, 0xc7aed40,  0x9b88b47b,
                                                           0xbcb45328, 0xb4e45849, 0xc6801965, 0xe5feee15};
  static constant constexpr storage<NLIMBS> m = {0xd59646e8, 0xec4f881f, 0x8163c701, 0x4e65c59e,
                                                 0x80a19de7, 0x2f7d1dc7, 0x7fda82a5, 0xa46e09d0,
                                                 0x331e9ae8, 0x38a0406c, 0xcf327917, 0x2760d74b};
  static constant constexpr storage<2 * NLIMBS> modulus_squared = {
    0x1c718e39, 0x26aa0000, 0x76382eab, 0x7ced6b1d, 0x62113cfd, 0x162c3383, 0x3e71b743, 0x66bf91ed,
    0x7091a049, 0x292e85a8, 0x86185c7b, 0x1d68619c, 0x978ef01,  0xf5314933, 0x16ddca6e, 0x50a62cfd,
    0x349e8bd0, 0x66e59e49, 0xe7046b4,  0xe2dc90e5, 0xa22f25e9, 0x4bd278ea, 0xb8c35fc7, 0x2a437a4};
  static constant constexpr storage<NLIMBS> montgomery_r = {0x2fffd,    0x76090000, 0xc40c0002, 0xebf4000b,
                                                            0x53c758ba, 0x5f489857, 0x70525745, 0x77ce5853,
                                                            0xa256ec6d, 0x5c071a97, 0xfa80e493, 0x15f65ec3};
  static constant constexpr storage<NLIMBS> montgomery_r_inv = {0x380b4820, 0xf4d38259, 0xd898fafb, 0x7fe11274,
                                                                0x14956dc8, 0x343ea979, 0x58a88de9, 0x1797ab14,
                                                                0x3c4f538b, 0xed5e6427, 0xe8fb0ce9, 0x14fec701};
};

// field instantiation
using bls12_381Scalar = Field<bls12_381ScalarConfig>;
using bls12_381BaseField = Field<bls12_381BaseFieldConfig>;