#pragma once

#include "field/field.metal.h"

/*
This file was automatically generated by icicle/icicle/backend/metal/scripts/gen_metal_shaders.py
To change the shader, change the template in icicle/icicle/backend/metal/scripts/templates
*/

struct bn254ScalarConfig {
  static constant constexpr uint NLIMBS = 8;
  static constant constexpr unsigned modulus_bit_count = 254;
  static constant constexpr unsigned num_of_reductions = 1;
  static constant constexpr storage<NLIMBS> modulus = {0xf0000001, 0x43e1f593, 0x79b97091, 0x2833e848,
                                                       0x8181585d, 0xb85045b6, 0xe131a029, 0x30644e72};
  static constant constexpr storage<NLIMBS> modulus_2 = {0xe0000002, 0x87c3eb27, 0xf372e122, 0x5067d090,
                                                         0x302b0ba,  0x70a08b6d, 0xc2634053, 0x60c89ce5};
  static constant constexpr storage<NLIMBS> modulus_4 = {0xc0000004, 0xf87d64f,  0xe6e5c245, 0xa0cfa121,
                                                         0x6056174,  0xe14116da, 0x84c680a6, 0xc19139cb};
  static constant constexpr storage<NLIMBS> neg_modulus = {0xfffffff,  0xbc1e0a6c, 0x86468f6e, 0xd7cc17b7,
                                                           0x7e7ea7a2, 0x47afba49, 0x1ece5fd6, 0xcf9bb18d};
  static constant constexpr storage<NLIMBS> rou = {0x725b19f0, 0x9bd61b6e, 0x41112ed4, 0x402d111e,
                                                   0x8ef62abc, 0xe0a7eb,   0xa58a7e85, 0x2a3c09f0};
  static constant constexpr storage<NLIMBS> m = {0xbe1de925, 0x620703a6, 0x9e880ae,  0x71448520,
                                                 0x68073014, 0xab074a58, 0x623a04a7, 0x54a47462};
  static constant constexpr storage<2 * NLIMBS> modulus_squared = {
    0xe0000001, 0x8c3eb27,  0xdcb34000, 0xc7f26223, 0x68c9bb7f, 0xffe9a62c, 0xe821ddb0, 0xa6ce1975,
    0x47b62fe7, 0x2c77527b, 0xd379d3df, 0x85f73bb0, 0x348d21c,  0x599a6f7c, 0x763cbf9c, 0x925c4b8};
  static constant constexpr storage<NLIMBS> montgomery_r = {0x4ffffffb, 0xac96341c, 0x9f60cd29, 0x36fc7695,
                                                            0x7879462e, 0x666ea36f, 0x9a07df2f, 0xe0a77c1};
  static constant constexpr storage<NLIMBS> montgomery_r_inv = {0x6db1194e, 0xdc5ba005, 0xe111ec87, 0x90ef5a9,
                                                                0xaeb85d5d, 0xc8260de4, 0x82c5551c, 0x15ebf951};
};

struct bn254BaseFieldConfig {
  static constant constexpr uint NLIMBS = 8;
  static constant constexpr unsigned modulus_bit_count = 254;
  static constant constexpr unsigned num_of_reductions = 1;
  static constant constexpr storage<NLIMBS> modulus = {0xd87cfd47, 0x3c208c16, 0x6871ca8d, 0x97816a91,
                                                       0x8181585d, 0xb85045b6, 0xe131a029, 0x30644e72};
  static constant constexpr storage<NLIMBS> modulus_2 = {0xb0f9fa8e, 0x7841182d, 0xd0e3951a, 0x2f02d522,
                                                         0x302b0bb,  0x70a08b6d, 0xc2634053, 0x60c89ce5};
  static constant constexpr storage<NLIMBS> modulus_4 = {0x61f3f51c, 0xf082305b, 0xa1c72a34, 0x5e05aa45,
                                                         0x6056176,  0xe14116da, 0x84c680a6, 0xc19139cb};
  static constant constexpr storage<NLIMBS> neg_modulus = {0x278302b9, 0xc3df73e9, 0x978e3572, 0x687e956e,
                                                           0x7e7ea7a2, 0x47afba49, 0x1ece5fd6, 0xcf9bb18d};
  static constant constexpr storage<NLIMBS> m = {0x19bf90e5, 0x6f3aed8a, 0x67cd4c08, 0xae965e17,
                                                 0x68073013, 0xab074a58, 0x623a04a7, 0x54a47462};
  static constant constexpr storage<2 * NLIMBS> modulus_squared = {
    0x275d69b1, 0x3b5458a2, 0x9eac101,  0xa602072d, 0x6d96cadc, 0x4a50189c, 0x7a1242c8, 0x4689e95,
    0x34c6b38d, 0x26edfa5c, 0x16375606, 0xb00b8551, 0x348d21c,  0x599a6f7c, 0x763cbf9c, 0x925c4b8};
  static constant constexpr storage<NLIMBS> montgomery_r = {0xc58f0d9d, 0xd35d438d, 0xf5c70b3d, 0xa78eb28,
                                                            0x7879462c, 0x666ea36f, 0x9a07df2f, 0xe0a77c1};
  static constant constexpr storage<NLIMBS> montgomery_r_inv = {0x14afa37,  0xed84884a, 0x278edf8,  0xeb202285,
                                                                0xb74492d9, 0xcf63e9cf, 0x59e5c639, 0x2e671571};
};

// field instantiation
using bn254Scalar = Field<bn254ScalarConfig>;
using bn254BaseField = Field<bn254BaseFieldConfig>;